name: CI - Terraform + Ansible

on:
  push:
    branches: [ snap-1 ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform apply (create infra)
        id: tf_apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Generate dynamic inventory
        run: bash ansible/generate_inventory.sh

      - name: Show generated inventory (debug)
        run: |
          echo "--- INVENTORY ---"
          cat ansible/inventory.ini | cat -A
          echo "--- END INVENTORY ---"



      - name: Show generated inventory (sanity)
        run: sed -n '1,200p' ansible/inventory.ini || true

      - name: Install Python and Ansible (on runner)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 python3-pip ssh
          python3 -m pip install --upgrade pip
          python3 -m pip install "ansible>=8.0"

      - name: Run Ansible playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook site.yml -i inventory.ini --private-key ci_id_rsa -u ec2-user
